const loopTypes = {
  NEXT_STEP: 'NEXT_STEP',
  FIRST_WORD: 'FIRST_WORD',
  NEXT_WORD: 'NEXT_WORD',

  //Steps Manager :
  GO_TO_WORD_INTRO: 'GO_TO_WORD_INTRO',
  GO_TO_WORD_SUGG_CARD_BUILDER: 'GO_TO_WORD_SUGG_CARD_BUILDER',
  GO_TO_WORD_FROM_SCRATCH_BUILDER: 'GO_TO_WORD_FROM_SCRATCH_BUILDER',
  GO_TO_WORD_OUTRO: 'GO_TO_WORD_OUTRO',
  GO_TO_THREE_PLUS: 'GO_TO_THREE_PLUS',

  SET_ERRORS: 'SET_ERRORS',
  RESET_STEPS: 'RESET_STEPS',
  ADD_TO_THREE_WORDS_STEPS: 'ADD_TO_THREE_WORDS_STEPS',
  GO_TO_FINAL_LOOP_SCREEN: 'GO_TO_FINAL_LOOP_SCREEN',
  SET_WORDS_BAG: 'SET_WORDS_BAG',
};

export default loopTypes;
