const localTypes = {
  ADD_TO_LOCAL: 'ADD_TO_LOCAL',
  REMOVE_FROM_LOCAL: 'REMOVE_FROM_LOCAL',
  EDIT_LOCAL: 'EDIT_LOCAL',
  ADD_THIS_BAG_TO_LOCAL: 'ADD_THIS_BAG_TO_LOCAL',
  CLEAR_REDUX_PERSIST_BAGS: 'CLEAR_REDUX_PERSIST_BAGS',
  ADD_SOUNDS: 'ADD_SOUNDS',
};

export default localTypes;
