const wordBagTypes = {
  ADD_WORD_TO_BAG: 'ADD_WORD_TO_BAG',
  REMOVE_WORD_FROM_BAG: 'REMOVE_WORD_FROM_BAG',
  CREATE_NEW_BAG: 'CREATE_NEW_BAG',
  CREATING_NEW_BAG: 'CREATING_NEW_BAG',
  NEW_BAG_CREATED_SUCCESSFULY: 'NEW_BAG_CREATED_SUCCESSFULY',
  LOADING_HANDLE: ' LOADING_HANDLE',
  CLEAR_WORDS_BAG: 'CLEAR_WORDS_BAG',
};

export default wordBagTypes;
